### ISSUE TITLE
Conflicts with Logger and Click inside of monitored script.

### ISSUE THREAD

**Issue by JuanPedroGHM** [Helmholtz-AI-Energy/perun#71]
1) Logging to sys.output not shown when perun is active.
2) Scripts using click command line argument parser do not end properly.

Example error: 
```python
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
   File "/usr/lib64/python3.8/multiprocessing/popen_fork.py", line 27, in poll
	pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
   File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
	self.run()
   File "/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
	self._target(*self._args, **self._kwargs)
   File "/path/to/venv/lib64/python3.8/site-packages/perun/perun.py", line 284, in perunSubprocess
	while not stop_event.wait(sampling_rate):
   File "/usr/lib64/python3.8/multiprocessing/synchronize.py", line 349, in wait
	self._cond.wait(timeout)
   File "/usr/lib64/python3.8/multiprocessing/synchronize.py", line 261, in wait
	return self._wait_semaphore.acquire(True, timeout)
```

**Comment by JuanPedroGHM** [comment]
Best possible solution, get rid of click, use argparse. One less dependency
